name: Common

on:
  workflow_call:
    inputs:
      workspace:
        required: true
        type: string
      working_directory:
        required: true
        type: string

jobs:
  plan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.workspace }}

      - run: echo "test"

      - run: echo ${{ inputs.working_directory }}
