name: Demo

# The workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  demo:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.branch-deploy.outputs.environment }}
    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v9.0.0

      - name: Test Run
        run: echo "test run"

      - name: Noop Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
        run: echo "Noop Deploy!"

      - name: Regular Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: echo "Regular Deploy!"

      - name: Production Noop Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' && steps.branch-deploy.outputs.environment == 'production' }}
        run: echo "Production Noop Deploy!"

      - name: Production Regular Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && steps.branch-deploy.outputs.environment == 'production' }}
        run: echo "Production Regular Deploy!"

      - name: Staging Noop Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' && steps.branch-deploy.outputs.environment == 'staging' }}
        run: echo "Staging Noop Deploy!"

      - name: Staging Regular Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && steps.branch-deploy.outputs.environment == 'staging' }}
        run: echo "Staging Regular Deploy!"
  result:
    needs: [demo]
    runs-on: ubuntu-latest
    environment: ${{ needs.demo.outputs.environment }}
    steps:
      - name: Env Test
        run: echo ${{ vars.TEST }}
