name: Demo

# The workflow to execute on is comments that are newly created
on:
  issue_comment:
    types: [created]
    paths:
      - "test/**"
      - .github/workflows/demo.yml

# Permissions needed for reacting and adding comments for IssueOps commands
permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  demo:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.branch-deploy.outputs.environment }}
      project: ${{ steps.set-outputs.outputs.project }}
    steps:
      - name: branch-deploy
        id: branch-deploy
        uses: github/branch-deploy@v9.0.0
        with:
          environment_targets: staging-demo,production-demo

      - name: Test Run
        run: echo "test run"

      - name: Noop Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' }}
        run: echo "Noop Deploy!"

      - name: Regular Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' }}
        run: echo "Regular Deploy!"

      - name: Production Noop Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' && steps.branch-deploy.outputs.environment == 'production' }}
        run: echo "Production Noop Deploy!"

      - name: Production Regular Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && steps.branch-deploy.outputs.environment == 'production' }}
        run: echo "Production Regular Deploy!"

      - name: Staging Noop Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop == 'true' && steps.branch-deploy.outputs.environment == 'staging' }}
        run: echo "Staging Noop Deploy!"

      - name: Staging Regular Deploy
        if: ${{ steps.branch-deploy.outputs.continue == 'true' && steps.branch-deploy.outputs.noop != 'true' && steps.branch-deploy.outputs.environment == 'staging' }}
        run: echo "Staging Regular Deploy!"

      - name: example
        if: steps.branch-deploy.outputs.continue == 'true'
        id: set-outputs
        run: |
          PARAMS=${{ steps.branch-deploy.outputs.params }}
          IFS=',' read -ra PARAM_ARRAY <<< "$PARAMS"
          for i in "${PARAM_ARRAY[@]}"; do
            KEY=$(echo $i | awk -F'=' '{print $1}')
            VALUE=$(echo $i | awk -F'=' '{print $2}')
            eval "$KEY=$VALUE"
            echo "::set-output name=$KEY::$VALUE"
          done

  result:
    needs: [demo]
    runs-on: ubuntu-latest
    environment: ${{ needs.demo.outputs.environment }}
    steps:
      - name: Env Test
        run: echo ${{ vars.TEST }}

      - name: Env Test
        run: echo ${{ needs.demo.outputs.project }}
